# Generated by Django 3.2.3 on 2021-05-24 12:21

from datetime import datetime
from django.db import models, migrations


def load_students(apps, schema_editor):
    Student = apps.get_model("homework_tracker_db", "Student")

    Student(first_name='Ivan', last_name='Pomerancev').save()
    Student(first_name='Gleb', last_name='Maxin').save()
    Student(first_name='Aleksey', last_name='Smirnov').save()


def load_teachers(apps, schema_editor):
    Teacher = apps.get_model("homework_tracker_db", "Teacher")

    Teacher(first_name='Maxim', last_name='Vernik').save()
    Teacher(first_name='Viktor', last_name='Petek').save()
    Teacher(first_name='Olga', last_name='Mixas').save()


def load_homeworks(apps, schema_editor):
    Homework = apps.get_model("homework_tracker_db", "Homework")

    Homework(text='OOP', deadline=5, created='2020-12-19 09:26:03.478039').save()
    Homework(text='Databases', deadline=10, created='2020-11-01 10:26:03.478039').save()
    Homework(text='Functions', deadline=3, created='2020-10-04 12:36:03.478039').save()


def load_homework_results(apps, schema_editor):
    HomeworkResult = apps.get_model("homework_tracker_db", "HomeworkResult")

    HomeworkResult(homework_id=1, student_id=2, solution='everything is done',
                   created=datetime(2020, 12, 19, 9, 26, 3, 478039)).save()
    HomeworkResult(homework_id=1, student_id=3, solution='done',
                   created=datetime(2020, 11, 1, 10, 26, 3, 478039)).save()
    HomeworkResult(homework_id=2, student_id=2, solution="I've done",
                   created=datetime(2020, 10, 4, 12, 36, 3, 478039)).save()


class Migration(migrations.Migration):
    dependencies = [
        ('homework_tracker_db', '0001_initial_migration'),
    ]

    operations = [
        migrations.RunPython(load_students),
        migrations.RunPython(load_teachers),
        migrations.RunPython(load_homeworks),
        migrations.RunPython(load_homework_results)
    ]
